name: Second 

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:

      my_name: "Artur"

    steps:
      - name: First variable
        run: echo "Hello, $my_name"
